// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxIWAuqhMh20HDGiMx2X1YorKqYUrkWtc',
    appId: '1:200830186800:web:6c05cadde4e9b5da7504f5',
    messagingSenderId: '200830186800',
    projectId: 'student-attendance-app-0-2186f',
    authDomain: 'student-attendance-app-0-2186f.firebaseapp.com',
    storageBucket: 'student-attendance-app-0-2186f.firebasestorage.app',
    measurementId: 'G-EZ904CSQP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIDB_EiCsQizDaC5TJyCcoDwGKQJ0lbl8',
    appId: '1:200830186800:android:cf29cc4befac97ad7504f5',
    messagingSenderId: '200830186800',
    projectId: 'student-attendance-app-0-2186f',
    storageBucket: 'student-attendance-app-0-2186f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0tePDsx7wVThjdgR_3aPjsk7I_VwkaoE',
    appId: '1:200830186800:ios:5dedbb1f68a7571e7504f5',
    messagingSenderId: '200830186800',
    projectId: 'student-attendance-app-0-2186f',
    storageBucket: 'student-attendance-app-0-2186f.firebasestorage.app',
    iosBundleId: 'com.example.staffAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0tePDsx7wVThjdgR_3aPjsk7I_VwkaoE',
    appId: '1:200830186800:ios:5dedbb1f68a7571e7504f5',
    messagingSenderId: '200830186800',
    projectId: 'student-attendance-app-0-2186f',
    storageBucket: 'student-attendance-app-0-2186f.firebasestorage.app',
    iosBundleId: 'com.example.staffAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxIWAuqhMh20HDGiMx2X1YorKqYUrkWtc',
    appId: '1:200830186800:web:1a165e01a59f31ea7504f5',
    messagingSenderId: '200830186800',
    projectId: 'student-attendance-app-0-2186f',
    authDomain: 'student-attendance-app-0-2186f.firebaseapp.com',
    storageBucket: 'student-attendance-app-0-2186f.firebasestorage.app',
    measurementId: 'G-H8RZWTLPPX',
  );
}
